apiVersion: v1
kind: Pod
metadata:
  name: warp-bench-manual
  namespace: minio-config
spec:
  containers:
  - name: warp
    image: ghcr.io/qjoly/warp-bench:0.9.0
    env:
    - name: WARP_HOST
      value: "minio"
    - name: WARP_ACCESS_KEY
      value: access_key
    - name: WARP_SECRET_KEY
      value: secret_key
    - name: WARP_TLS
      value: "true"
    - name: BENCH_MODE
      value: "mixed"
    - name: DURATION
      value: 1m
    - name: EXTRA_ARGS
      value: "--bucket kube-put"
    # command: ["/bin/sh", "-c", "sleep infinity"] # If you want to run it manually by exec
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "128Mi"
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault